/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * */

export const videos = [
  {
    _id: "kKGPLQaZmHw",
    title: "Journey of a Computer Science Engineer - A talk by Tanay Pratap",
    category: "stories",
    description:
      "Tanay Pratap is a software engineer at Microsoft and a mentor students love to have. Whether it's college grads, corporate tech training, regular JS/React meetups or hot shot international conference.",
    creator: "Developer Student",
    likes: 235,
    views: 3396,
    date: "16-11-2021",
    time: "1:10:48",
  },
  {
    _id: "Sd3_rjKQf24",
    title: "How does snow form?",
    category: "facts",
    description:
      "Clouds are made up of supercooled water droplets. These water droplets are colder than freezing because pure water won't freeze until minus 40 or unless it has something to latch onto like dust or dirt. In the clouds, those little bits of dust and dirt are called ice nuclei.",
    creator: "Storm Shield App",
    likes: 264,
    views: 2617,
    date: "30-01-2015",
    time: "1:38",
  },
  {
    _id: "3CWJNqyub3o",
    title: "Jingle Bells with Lyrics | Christmas Songs HD",
    category: "songs",
    description:
      "Popular Christmas songs! Jingle Bells is beautifully sung by our top talented choir. Great for Christmas performances, concerts, choirs and churches. Join us on this merry sing along journey! Merry Christmas.",
    creator: "Songs and Carols",
    likes: 590,
    views: 1354,
    date: "29-08-2015",
    time: "1:46",
  },
  {
    _id: "B9l-2J7Nkbo",
    title: "23 Magical decor ideas",
    category: "decorations",
    description:
      "Today you will find New Year's Eve party ideas to make your party absolutely incredible! You will find a lot of fabulous decorating ideas that will amaze your guests! Our craft projects won't take a lot of time and require a minimum amount of supplies.",
    creator: "5-Minute DECOR",
    likes: 440,
    views: 4678,
    date: "30-11-2018",
    time: "9:09",
  },
  {
    _id: "TbQm5doF_Uc",
    title: "Disney's Frozen Official Trailer",
    category: "movies",
    description: "On Digital HD Now and Blu-ray 3/18",
    creator: "Walt Disney Animation Studios",
    likes: 6800,
    views: 7647,
    date: "27-07-2013",
    time: "2:23",
  },
  {
    _id: "jEDaVHmw7r4",
    title: "Home Alone (1990) Trailer #1",
    category: "movies",
    description:
      "Home Alone (1990) Trailer #1: Check out the trailer starring Macaulay Culkin, Joe Pesci, and Daniel Stern! Be the first to watch",
    creator: "Movieclips Classic Trailers",
    likes: 1000,
    views: 2313,
    date: "19-11-1990",
    time: "2:14",
  },
  {
    _id: "taE3PwurhYM",
    title: "Klaus | Official Trailer | Netflix",
    category: "movies",
    description:
      "This holiday season, discover the unlikely friendship that launched a legend. Watch Klaus on #Netflix.",
    creator: "Netflix",
    likes: 9000,
    views: 10545,
    date: "07-10-2019",
    time: "2:46",
  },
  {
    _id: "ao2Jfm35XeE",
    title: "The Snowflake Mystery",
    category: "facts",
    description:
      "Dr Ken Libbrecht is the world expert on snowflakes, designer of custom snowflakes, snowflake consultant for the movie Frozen - his photos appear on postage stamps all over the world.",
    creator: "Veritasium",
    likes: 2653,
    views: 3333,
    date: "01-12-2021",
    time: "18:48",
  },
  {
    _id: "5h9VDUNtoto",
    title: "Home Alone 2: Lost in New York (1992) Trailer #1",
    category: "movies",
    description:
      "Home Alone 2: Lost in New York (1992) Trailer #1: Check out the trailer starring Macaulay Culkin, Joe Pesci, and Daniel Stern! Be the first to watch",
    creator: "Movieclips Classic Trailers",
    likes: 2500,
    views: 47056,
    date: "20-11-1992",
    time: "1:13",
  },
  {
    _id: "bYoEz9nPAi4",
    title: "Top Interesting facts about technology",
    category: "facts",
    description:
      "Learn 10 Interesting facts about technology. Today I'm sharing some of the interesting facts about technology. Knowledge about technology is a must these days.In this cutting-edge world of technology brush up your knowledge with these interesting facts about technology.",
    creator: "Fact Life Official",
    likes: 115,
    views: 4898,
    date: "11-04-2021",
    time: "5:45",
  },
  {
    _id: "WhJYZqYO-Fk",
    title: "6 Easy and Attractive Paper Wall Hangings - DIY Christmas Paper Decoration Ideas",
    category: "decorations",
    description:
      "Simple and Attractive Paper Wall hanging - DIY Christmas Paper Decoration Ideas 6 Easy and Simple Wall Hanging Ideas for Wall Decoration with Paper",
    creator: "Two Points Crafts",
    likes: 110,
    views: 616,
    date: "27-08-2021",
    time: "12:25",
  },
  {
    _id: "WinpUwqRFX4",
    title: "Amazing CHRISTMAS Decorations || 5-Minute Decor Ideas You'll Want to Make!",
    category: "decorations",
    description:
      "CREATIVE DECOR PROJECTS FOR YOUR HOME We prepared amazing Christmas decorations made from pasta and ideas for Christmas that will bring joy to your home!",
    creator: "5-Minute DECOR",
    likes: 780,
    views: 980,
    date: "16-11-2021",
    time: "12:31",
  },
  {
    _id: "bzrxmFCrN7Q",
    title: "10 Christmas Decoration Ideas || 🎄⭐Paper Decoration ideas for Christmas",
    category: "decorations",
    description:
      "Christmas Decoration Ideas Using Paper In this video we are making a beautiful flower for you. We hope this video will be interesting to you.",
    creator: "Arts&Crafts",
    likes: 560,
    views: 4581,
    date: "21-12-2019",
    time: "34:09",
  },
  {
    _id: "g-OF7KGyDis",
    title: "We Wish You a Merry Christmas with Lyrics",
    category: "songs",
    description:
      "Popular Christmas carol We Wish You a Merry Christmas beautifully sung by top talented choir - great for Christmas concerts, performances, choirs and church 🎵",
    creator: "Songs and Carols",
    likes: 657,
    views: 1216,
    date: "07-12-2014",
    time: "2:01",
  },
  {
    _id: "a171hw91QjI",
    title: "The Story of Jeff",
    category: "stories",
    description:
      "After humble beginnings working in an small Albuquerque McDonald's, Jeff Bezos has worked his way up the ladder of life ending up as the Owner / CEO of Amazon, The Washington Post and Blue Origin.",
    creator: "SunnyV2",
    likes: 2754,
    views: 10401,
    date: "18-02-2021",
    time: "26:28",
  },
  {
    _id: "l2mI-aqz4vo",
    title: "Sundar Pichai Success Story | GOOGLE CEO Biography | Startup Stories India",
    category: "stories",
    description:
      "Startup Stories Proudly presents the success story of Google CEO Sundar Pichai. This biography video shows how this small town boy from Chennai became India's Pride, by heading the biggest company in the world.",
    creator: "Startup Stories",
    likes: 413,
    views: 2500,
    date: "19-01-2017",
    time: "7:34",
  },
  {
    _id: "vai3Vh234EE",
    title: "Becoming Elon Musk (Full Documentary)",
    category: "stories",
    description:
      "Elon Musk is a business magnate, entrepreneur and engineer, who despite coming from humble beginnings in South Africa, is slowly becoming the individual most trusted with the future of human existence. But it's safe to say - It hasn't been all smooth sailing for Elon Musk. From sleeping on a couch in his first office, to 3 divorces, to 2 days from bankruptcy in 2008, it's certainly been a bumpy ride for the Neuralink, Tesla and SapceX CEO. Joe Rogan, the first planned trip to Mars, as well as outrageous goals to stop traffic as it is, are just 3 things we will discuss in this video. This, is the story of Elon Musk.",
    creator: "SunnyV2",
    likes: 7200,
    views: 41133,
    date: "30-09-2020",
    time: "26:40",
  },
  {
    _id: "3te6TZztQ00",
    title: "65 Quick Facts to Make You the Most Interesting Person in The Room",
    category: "facts",
    description:
      "Sometimes it seems that you’ve seen so much in this life that nothing will be able to surprise you ever again. And then you accidentally overheard someone mentions something amazing, like the fact that Charlie Chaplin once entered a Charlie Chaplin lookalike contest… and lost it! Yeah... There are a looot of strange things in the world.",
    creator: "BRIGHT SIDE",
    likes: 770,
    views: 4821,
    date: "15-09-2019",
    time: "11:13",
  },
  {
    _id: "aAkMkVFwAoo",
    title: "Mariah Carey - All I Want for Christmas Is You",
    category: "songs",
    description: "All I Want For Christmas Is You by Mariah Carey (Make My Wish Come True Edition)",
    creator: "Mariah Carey",
    likes: 3500,
    views: 3700,
    date: "20-12-2019",
    time: "4:03",
  },
];
